### ISSUE TITLE
release doesnt work yet

### ISSUE THREAD

**Issue by sw-yx** [breadthe/sd-buddy#1] opened 2022-09-04 06:13 UTC
just tried downloading the first releases

![image](https://user-images.githubusercontent.com/6764957/188300051-365e0962-c90f-46b6-8bf7-6677c1229b70.png)

just a heads up in case it helps

![image](https://user-images.githubusercontent.com/6764957/188300065-62d518c2-e675-4d02-afc6-c0dc9675d4b1.png)

**Comment by sw-yx** [comment] 2022-09-04 06:43
i was able to build and run from source. lots of little bugs, sending in a fix (with full understanding that you can reject them if you wish)

**Comment by breadthe** [comment] 2022-09-04 17:59
Hey thanks, I appreciate this!
I admit the build didn't always work for me either. I had to build multiple times and I uploaded the version that worked for me. I'm not sure exactly what the problem is.
I'm about to release a new version though.

**Comment by breadthe** [comment] 2022-09-04 19:08
I'm getting this when I try to open it from Applications. However, I found that if I hit Reopen a few times it will eventually open.

![CleanShot 2022-09-04 at 14 06 11@2x](https://user-images.githubusercontent.com/17433578/188329590-49fd8f85-021d-44c1-a088-40f5aae7df86.png)

**Comment by breadthe** [comment] 2022-09-04 20:11
I *think* I might have fixed this somewhat. I had a feeling it came from calling get/set on the `tauri-settings` library synchronously, so I made them async.

**Comment by breadthe** [comment] 2022-09-06 00:01
Scratch what I said above. The build works on the machine which created it, but not on a different M1 Mac. Obviously a Tauri thing (build config perhaps?). I haven't found any issues describing this problem but I'll circle back to it later.

**Comment by sw-yx** [comment] 2022-09-06 06:38
sounds like Tauri needs a lot of config to get it right :/

**Comment by richardawe** [comment] 2022-09-06 14:33
error: no such subcommand: `tauri`

        Did you mean `miri`?

**Comment by danawoodman** [comment] 2022-09-07 04:35
> error: no such subcommand: `tauri`
> 
> ```
>     Did you mean `miri`?
> ```

Sounds like you don't have it installed globally. Try this instead:

```
npm run tauri
```

**Comment by caesar** [comment] 2022-09-10 19:35
A solution might be to build with GitHub Actions, [Tauri has a preconfigured action](https://github.com/tauri-apps/tauri-action) which is quite easy to set up ([more info here](https://tauri.app/v1/guides/building/cross-platform)). GH Actions is free for open source projects I believe.

**Comment by breadthe** [comment] 2022-09-11 15:38
Yes! This is the next thing I want to try as soon as I fix a couple bugs and wrap up some loose ends.

**Comment by breadthe** [comment] 2022-09-11 22:48
I'm closing this for now as resolved starting with [v0.7.2](https://github.com/breadthe/sd-buddy/releases/tag/v0.7.2) since it looks like the GH Action provided by Tauri did the trick. I tested the `.dmg` on two different machines and it worked.

There are also Linux and Windows builds. I'd love for someone to test the Linux one. There's a good chance it'll work though I can't guarantee it. The Windows build will most likely NOT work based on how the logic works in the Rust code.

**Closed by breadthe** 2022-09-11 22:48 UTC

**Comment by caesar** [comment] 2022-09-11 23:30
The release build runs, but strangely, I'm getting the same error ("image error") I reported in #15. I've no idea if the cause is the same. I've also tried building locally, and can confirm that also doesn't work… I'm having trouble debugging, because any kind of debug build I make works fine, but release builds don't work! Very odd.

**Comment by breadthe** [comment] 2022-09-11 23:51
Aw that's a bummer. "It works for me" doesn't help you much. Unless I can think of a solution, may I suggest adding some more error handling to the Rust code and passing that to the front-end? I'm not exactly sure where it fails. It could be that `direnv` doesn't like to run in release mode for some reason. Also, try playing around with the image parameters. Sometimes it fails for me for certain param combos.

**Comment by sw-yx** [comment] 2022-09-12 04:45
the way to elimiinate that last part is to run it in cli so you can make sure sd-buddy is the cause of the problem

**Comment by caesar** [comment] 2022-09-12 16:10
Yeah it's not a problem with the parameters – same parameters work fine in debug builds and from the CLI.

Interestingly, even in the release build, if I launch the binary from the command line (rather than double-clicking the app bundle in Finder) it also works fine. So I'm thinking this must have to do with the app's working directory – though in theory `.current_dir(stable_diffusion_directory)` should make that irrelevant I assume – or possible the environment.

I'll dig deeper when I have a chance, maybe tonight or tomorrow.

Probably not related to this issue anyway. More likely should be continuing discussion on #15 I guess…
